# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['run.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('servidor_app/templates', 'servidor_app/templates'),
        ('servidor_app/static', 'servidor_app/static'),
        ('servidor_app/instance', 'servidor_app/instance'),
        ('servidor_app/config.py', 'servidor_app/config.py'),
        ('.env', '.'),
    ],
    hiddenimports=[
        'flask',
        'flask_sqlalchemy',
        'flask_login',
        'sqlalchemy',
        'werkzeug',
        'jinja2',
        'dotenv',
        'pyngrok',
        'servidor_app',
        'servidor_app.controllers',
        'servidor_app.models',
        'servidor_app.services',
        'servidor_app.controllers.main_controller',
        'servidor_app.controllers.api_controller',
        'servidor_app.controllers.auth_controller',
        'servidor_app.controllers.file_api',
        'servidor_app.controllers.file_controller',
        'servidor_app.controllers.git_api',
        'servidor_app.controllers.sync_api',
        'servidor_app.models.user_model',
        'servidor_app.models.file_metadata_model',
        'servidor_app.models.file_system_model',
        'servidor_app.services.cache_service',
        'servidor_app.services.database_service',
        'servidor_app.services.metrics_service',
        'servidor_app.services.optimization_service',
        'servidor_app.services.server_info_service',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='servidor_app',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
